version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - letshorten:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
  redis:
    image: redis:alpine
    hostname: redis-local
    container_name: redis-local
    ports:
      - "6379:6379"

volumes:
  letshorten:
